apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nodejs-app
  name: nodejs-app
spec:
 replicas: 2
 selector:
   matchLabels:
     app: nodejs-app
 template:
   metadata:
     labels:
       app: nodejs-app
   spec:
     containers:
       - name: nodejs-app
         image: 440644114391.dkr.ecr.us-east-1.amazonaws.com/my-docker-repo:latestv4
         imagePullPolicy: Always
         ports:
         - containerPort: 3000
           name: http
           protocol: TCP
