version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    ports:
      - "5432:5432"

  backend:
    build: .
    depends_on:
      - db
    environment:
      PORT: ${PORT}
      DB_USER_NAME: ${DB_USER_NAME}
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: 5432
    ports:
      - "3000:3000"
    command: npm start
