apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodejs-app
    k8s-app: nodejs-app
  name: nodejs-app
spec:
  ports:
  - name: http
    protocol: TCP
    port: 3000
    targetPort: 3000
  type: LoadBalancer
  selector:
    app: nodejs-app
